fsi_news_archive:
    path: /news/archive/{page}
    defaults: { _controller: fsi_news.controller.news:archiveAction, page: 1 }

fsi_news:
    path: /news/{id}
    defaults: { _controller: fsi_news.controller.news:newsAction }
